In [1]:
import numpy as np
import math

### Loading Image

In [30]:
# Load P1 Image
def load_image(image_url):
    header = []
    with open(image_url, 'r') as f:
        for l in range(3):
            header.append(f.readline())
        y,x = [int(n) for n in header[2].split()]
        pixels = np.zeros((x, y)) # (7,24)
        for j in range(x):
            for k in range(y):
                pixel = f.read(1)
                if pixel in ['\n', ' ']:
                    pixel = f.read(1)
                pixels[j][k] = pixel
        return header, pixels.astype('int64')

### Store image

In [31]:
def store_image(image_url, img_data):
    header, pixels = img_data
    with open(image_url, 'w') as f:
        [f.write(l) for l in header]
        y,x = [int(n) for n in header[2].split()]
        for j in range(x):
            for k in range(y):
                f.write(str(int(pixels.item(j,k))))
            f.write('\n')
        return 0

### Add S&P noise to the image

In [5]:
def noisy(pixels):
    row,col = pixels.shape
    s_vs_p = 0.5
    amount = 0.04
    out = np.copy(pixels)
    # Salt mode
    num_salt = np.ceil(amount * pixels.size * s_vs_p)
    coords = [np.random.randint(0, i - 1, int(num_salt))
          for i in pixels.shape]
    out[coords] = 1
    # Pepper mode
    num_pepper = np.ceil(amount* pixels.size * (1. - s_vs_p))
    coords = [np.random.randint(0, i - 1, int(num_pepper))
          for i in pixels.shape]
    out[coords] = 0
    return out

In [6]:
header, pixels = load_image('teste/42.pbm')

In [7]:
pixels = noisy(pixels)

img = [header, pixels]
store_image('42-noised.pbm', img)

<ipython-input-5-a35c8f07ca02>:10: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out[coords] = 1
<ipython-input-5-a35c8f07ca02>:15: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  out[coords] = 0


0

In [3]:
def getValue(x, row, col):
    try:
        if row < 0 or col < 0:
            return 0
        return x.item(row, col)
    except IndexError:
        return 0

### Filtro da mediana

In [8]:
# Load Image
# header, pixels = load_image('fig_test.pbm')
header, pixels = load_image('42-noised.pbm')

In [28]:
def median_filter(pixels):    
    # create 3x3 matrix 
    m = np.zeros((3,3))
    
    # create temporary image
    P = np.zeros_like(pixels)

    print('Initializing filter...')
    x, y = pixels.shape
    for i in range(x):
        for j in range(y):
            # first pixel
            m[0][0] = getValue(pixels,i-1,j-1)
            m[0][1] = getValue(pixels,i-1,j)
            m[0][2] = getValue(pixels,i-1,j+1)
            m[1][0] = getValue(pixels,i,j-1)
            # center pixel
            m[1][1] = pixels[i][j]
            m[1][2] = getValue(pixels,i,j+1)
            m[2][0] = getValue(pixels,i+1,j-1)
            m[2][1] = getValue(pixels,i+1,j)
            # last pixel
            m[2][2] = getValue(pixels,i+1,j+1)

            # calculate median value of matrix m
            P[i][j] = math.trunc(np.median(m))

        print(format((i/x),".2%"))
    print("Done.")
    
    return P

In [11]:
# Create filtered image
img = [header, median_filter(pixels)]

Initializing filter...
0.00%
0.05%
0.09%
0.14%
0.18%
0.23%
0.27%
0.32%
0.36%
0.41%
0.45%
0.50%
0.55%
0.59%
0.64%
0.68%
0.73%
0.77%
0.82%
0.86%
0.91%
0.95%
1.00%
1.05%
1.09%
1.14%
1.18%
1.23%
1.27%
1.32%
1.36%
1.41%
1.45%
1.50%
1.55%
1.59%
1.64%
1.68%
1.73%
1.77%
1.82%
1.86%
1.91%
1.95%
2.00%
2.05%
2.09%
2.14%
2.18%
2.23%
2.27%
2.32%
2.36%
2.41%
2.45%
2.50%
2.55%
2.59%
2.64%
2.68%
2.73%
2.77%
2.82%
2.86%
2.91%
2.95%
3.00%
3.05%
3.09%
3.14%
3.18%
3.23%
3.27%
3.32%
3.36%
3.41%
3.45%
3.50%
3.55%
3.59%
3.64%
3.68%
3.73%
3.77%
3.82%
3.86%
3.91%
3.95%
4.00%
4.05%
4.09%
4.14%
4.18%
4.23%
4.27%
4.32%
4.36%
4.41%
4.45%
4.50%
4.55%
4.59%
4.64%
4.68%
4.73%
4.77%
4.82%
4.86%
4.91%
4.95%
5.00%
5.05%
5.09%
5.14%
5.18%
5.23%
5.27%
5.32%
5.36%
5.41%
5.45%
5.50%
5.55%
5.59%
5.64%
5.68%
5.73%
5.77%
5.82%
5.86%
5.91%
5.95%
6.00%
6.05%
6.09%
6.14%
6.18%
6.23%
6.27%
6.32%
6.36%
6.41%
6.45%
6.50%
6.55%
6.59%
6.64%
6.68%
6.73%
6.77%
6.82%
6.86%
6.91%
6.95%
7.00%
7.05%
7.09%
7.14%
7.18%
7.23%
7.27%
7.32%
7.36%

54.50%
54.55%
54.59%
54.64%
54.68%
54.73%
54.77%
54.82%
54.86%
54.91%
54.95%
55.00%
55.05%
55.09%
55.14%
55.18%
55.23%
55.27%
55.32%
55.36%
55.41%
55.45%
55.50%
55.55%
55.59%
55.64%
55.68%
55.73%
55.77%
55.82%
55.86%
55.91%
55.95%
56.00%
56.05%
56.09%
56.14%
56.18%
56.23%
56.27%
56.32%
56.36%
56.41%
56.45%
56.50%
56.55%
56.59%
56.64%
56.68%
56.73%
56.77%
56.82%
56.86%
56.91%
56.95%
57.00%
57.05%
57.09%
57.14%
57.18%
57.23%
57.27%
57.32%
57.36%
57.41%
57.45%
57.50%
57.55%
57.59%
57.64%
57.68%
57.73%
57.77%
57.82%
57.86%
57.91%
57.95%
58.00%
58.05%
58.09%
58.14%
58.18%
58.23%
58.27%
58.32%
58.36%
58.41%
58.45%
58.50%
58.55%
58.59%
58.64%
58.68%
58.73%
58.77%
58.82%
58.86%
58.91%
58.95%
59.00%
59.05%
59.09%
59.14%
59.18%
59.23%
59.27%
59.32%
59.36%
59.41%
59.45%
59.50%
59.55%
59.59%
59.64%
59.68%
59.73%
59.77%
59.82%
59.86%
59.91%
59.95%
60.00%
60.05%
60.09%
60.14%
60.18%
60.23%
60.27%
60.32%
60.36%
60.41%
60.45%
60.50%
60.55%
60.59%
60.64%
60.68%
60.73%
60.77%
60.82%
60.86%
60.91%
60.95%

In [13]:
# Store filtered image
if store_image('grupo_4_imagem_109?_linhas_423_palavras.pbm', img) == 0: print('Operation Successful!')

Operation Successful!


In [ ]:
"""
    Create a cross (+) element structured (lines x columns) with front in black, returning the element and how many lines and columns
"""
def create_cross_es(lines, columns):
    a = np.zeros([lines, columns])
    X = []
    Y = []
    
    lines = len(a) // 2
    columns = len(a[0]) // 2

    # preencher coluna com 1
    for index in range(len(a)):
        a[index][columns] = 1
        Y.append(columns)

    # preencher linha com 1
    for index in range(len(a[0])):
        a[lines][index] = 1
        X.append(index)

    return a, [X, Y]


"""
    Create a cross (+) element structured (lines x columns) with front in white, returning the element and how many lines and columns
"""
def create_cross_complements_es(lines, columns):
    a = np.ones([lines, columns])
    X = []
    Y = []

    lines = len(a) // 2
    columns = len(a[0]) // 2

    # preencher linha com 1
    for index in range(len(a[0])):
        a[lines][index] = 0
        X.append(index)

    # preencher coluna com 1
    for index in range(len(a)):
        a[index][columns] = 0
        Y.append(index)

    return a, [X, Y]
    
    
"""
    Create a line (|) element structured (lines x columns) with front in black, returning the element and how many lines and columns
"""
def create_line_es(lines, columns):
    a = np.zeros([lines, columns])
    X = []
    Y = []
    
    lines = len(a) // 2
    columns = len(a[0]) // 2

    # preencher coluna com 1
    for index in range(len(a)):
        a[index][columns] = 1
        Y.append(columns)

    return a, [X, Y]


"""
    Create a line (|) element structured (lines x columns) with front in white, returning the element and how many lines and columns
"""

def create_line_complements_es(lines, columns):
    a = np.ones([lines, columns])
    X = []
    Y = []

    lines = len(a) // 2
    columns = len(a[0]) // 2

    # preencher coluna com 1
    for index in range(len(a)):
        a[index][columns] = 0
        Y.append(index)

    return a, [X, Y]

### Objetivos (2ª etapa)

    1. Contagem de linhas e colunas;
    2. Detecção das palavras (circunscrição com retângulo) e;
    3. Possíveis recursos extras

## Operaçãos Morfológicas

### Definições básicas

#### Reflexão

É dada por: 

{$w | w = -b$, para todo b $\epsilon$ B}

Ou seja, com B conjunto de pixels (pontos bidimensionais) que representa um objeto em uma imagem, temos como resultado o conjunto de pontos em B cujas coordenadas (x,y) foram substituídas por (-x,-y)

In [4]:
def reflect(pixels):
    reflected = np.copy(pixels)
    for i in range(pixels.shape[0]):
        for j in range(pixels.shape[1]):
            ref_p = getValue(pixels,-i,-j)
            reflected[i][j] = ref_p
#             print(ref_p)
    return reflected

ES = np.array([0,1,0,1,1,1,0,1,0]).reshape(3,3)
ES
ES, reflect(ES)

(array([[0, 1, 0],
        [1, 1, 1],
        [0, 1, 0]]),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]))

#### Translação

É dada por:

$(B)_z=$ {$c | c = b + z$, para todo b $\epsilon$ B}

Onde B é o conjunto de pixels que representa um objeto em uma imagem, então $(B)_z$ é o conjunto de pontos em B, cujas coordenadas $(x,y)$ foram substituídas por $(x+z_1, y+z_2)$

In [24]:
def translate(pixels, z):
    translated = np.copy(pixels)
    z1, z2 = z
    for i in range(pixels.shape[0]):
        for j in range(pixels.shape[1]):
            translated[i][j] = getValue(pixels, i+z1, j+z2)
    return translated

z = (0,-1)
translate(ES, z)

array([[0, 0, 1],
       [0, 1, 1],
       [0, 0, 1]])

In [20]:
translate(np.array([5,5,5,5]).reshape(2,2), [1,1])

array([[5, 0],
       [0, 0]])

### Erosão

    0. varrer com o ES a matriz de entrada
    1. onde o formato do ES casar com a imagem original, aplicar no pixel central do ES o valor 1 na imagem de saída
    2. caso contrário aplique 0
    
    

In [27]:
def erode(pixels, ES):

    X = pixels.shape[0] + ES.shape[0] - 1
    Y = pixels.shape[1] + ES.shape[1] - 1
    dst = np.zeros((X, Y))
    img_erode = np.zeros(pixels.shape)

    for i in range(pixels.shape[0]):
        for j in range(pixels.shape[1]):
            dx = i + np.int32((ES.shape[0] - 1) / 2)
            dy = j + np.int32((ES.shape[1] - 1) / 2)

#             dst[i+1, j+1] = getValue(pixels, i, j)
            dst[dx, dy] = pixels.item(i, j)


    for i in range(pixels.shape[0]):
        for j in range(pixels.shape[1]):
            neighbors = dst[i:i + ES.shape[0], j:j + ES.shape[1]]
            img_erode[i,j] = neighbors[ES == True].min()

    return img_erode

# pixels = np.array([0, 0, 0, 0, 1, 1, 0, 1, 1]).reshape([3, 3])
# ES = np.array([0, 0, 0, 0, 1, 1, 0, 0, 0]).reshape([3, 3])

A = np.array([
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
    0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
    0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=np.uint8).reshape([ 6, 12 ])

X = np.array([
    0, 0, 0, 0, 0,
    0, 1, 1, 1, 0,
    0, 1, 1, 1, 0,
    0, 1, 1, 1, 0,
    0, 0, 0, 0, 0], dtype=np.uint8).reshape([5, 5])

erode(A, X), A, X

(array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8),
 array([[0, 0, 0, 0, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0],
        [0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0]], dtype=uint8))

In [131]:
# es = np.array([0,0,0,0,1,0,0,0,0]).reshape(3,3)
es2 = np.arange(25).reshape(5,5)
erode(ES, es2), es2

(2, 3)
0 0 0
0 1 1
0 2 2
0 3 3
1 0 5
1 1 6
1 2 7
1 3 8
2 0 10
2 1 11
2 2 12
2 3 13
3 0 15
3 1 16
3 2 17
3 3 18


(array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]),
 array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]))

### Passos para dilatação

    0. criar uma matriz semelhante à original:
        output = np.zeros_like(imagem)
    1. pegar todos os pixels de valor 1 da imagem:
        x,y = np.where(image == 1)
    2. iterar os pixels filtrados da imagem original com o ES:
        for i in range(x):
           for j in range(y):
                (para cada pixel do kernel) output[i][j] = max()

### Dilatação

In [29]:
def dilate(pixels, ES):

    X = pixels.shape[0] + ES.shape[0] - 1
    Y = pixels.shape[1] + ES.shape[1] - 1
    dst = np.zeros((X, Y))
    img_erode = np.zeros(pixels.shape)

    for i in range(pixels.shape[0]):
        for j in range(pixels.shape[1]):
            dx = i + np.int32((ES.shape[0] - 1) / 2)
            dy = j + np.int32((ES.shape[1] - 1) / 2)

            dst[dx, dy] = pixels.item(i, j)

    for i in range(pixels.shape[0]):
        for j in range(pixels.shape[1]):
            neighbors = dst[i:i + ES.shape[0], j:j + ES.shape[1]]
            img_erode[i,j] = neighbors[ES == True].max()

    return output

pixels = np.array([0, 0, 0, 0, 1, 0, 0, 0, 0]).reshape([3, 3])
ES = np.array([0, 0, 0, 0, 1, 1, 0, 0, 0]).reshape([3, 3])

dilate(pixels, ES)

array([[0., 0., 0.],
       [1., 1., 0.],
       [0., 0., 0.]])

### Abertura

In [ ]:
img = load_image('./teste/Cthulhu.pbm')

In [ ]:
header, pixels = img

eroded_img = erode(pixels, X)

if store_image('erosao-cthulhu.pbm', [header, eroded_img])  == 0: print("success!")

In [38]:
img = load_image('./erosao-cthulhu.pbm')

In [39]:
header, pixels = img

dilated_img = dilate(pixels, X)

if store_image('abertura-cthulhu.pbm', [header, dilated_img])  == 0: print("success!")

success!


### Fechamento

In [40]:
img = load_image('./teste/Cthulhu.pbm')

In [41]:
header, pixels = img

dilated_img = dilate(pixels, X)

if store_image('dilatacao-cthulhu.pbm', [header, dilated_img])  == 0: print("success!")

success!


In [42]:
img = load_image('./dilatacao-cthulhu.pbm')

In [43]:
header, pixels = img

eroded_img = erode(pixels, X)

if store_image('fechamento-cthulhu.pbm', [header, eroded_img])  == 0: print("success!")

success!
